ALTER TABLE leads      ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE leads      ADD COLUMN updated_at  TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE leads      ADD COLUMN deleted_at  TIMESTAMPTZ;

ALTER TABLE companies  ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE companies  ADD COLUMN updated_at  TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE locations  ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE sources    ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE skills     ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT now();